### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by Leon123-tech** [haiciyang/SANAC#1]

**Comment by haiciyang** [comment]
Hi! The model was missed in the last commit. I will try to regenerate and upload it soon.

**Comment by haiciyang** [comment]
> _No description provided._

**Comment by Leon123-tech** [comment]
Hi Professor:


&nbsp; &nbsp; Thank you for reading!
&nbsp; &nbsp; I am a senior&nbsp; at Xi'an University of Posts and Telecommunications, China.I'm working on my graduation project recently, and I'm very interested in your thesis "SOURCE-AWARE NEURAL SPEECH CODING FOR NOISY SPEECH COMPRESSION". I found the source program on the website provided by your paper, but the training model file is missing. I tried to train by myself, but I didn't succeed because of the limitation of equipment.&nbsp;
&nbsp; &nbsp; Can you provide me with the missing documents?I promise they will be used only for research purposed.
&nbsp; &nbsp; Thank you very much for your kind consideration and I am looking forward to your early reply.

**Comment by haiciyang** [comment]
Hello Leon,

Thank you again for your interest. We are currently rebuilding the system, and will soon update all the codes and files. And that process will take weeks. 

Seems you are in a hurry, and I'm willing to help. You can email me at hy17@iu.edu. We can discuss the problem you are facing and I'm happy to provide the source code if needed.
Haici
